FROM {{ PLANGRID_DOCKER_REPO }}/pg-docker:master
MAINTAINER plangrid

RUN apt-get update && apt-get install -y --no-install-recommends \
    libfreetype6-dev \
    libjpeg-dev \
    libpng-dev \
    zlib1g-dev

RUN mkdir /root/home
WORKDIR /root/home

COPY requirements/ ./requirements

COPY ./ .
