FROM {{ PLANGRID_DOCKER_REPO }}/pg-docker:master
MAINTAINER plangrid

# Most of these dependencies are for pyenv, unfortunately
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libncurses5-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libffi-dev \
    liblzma-dev \
    python-openssl \
    libjpeg-dev \
    libpng-dev \
    zlib1g-dev

RUN mkdir /root/home
WORKDIR /root/home

RUN curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="${PYENV_ROOT}/bin:${PYENV_ROOT}/shims:${PATH}"
RUN pyenv install 3.5.6
RUN pyenv install 3.6.8
RUN pyenv install 2.7.15
RUN pyenv rehash

COPY ./Makefile Makefile
RUN make setup

COPY ./ .
