# -*- coding: utf-8 -*-
TEXT_ALIGN_LEFT = 'left'
TEXT_ALIGN_CENTER = 'center'
TEXT_ALIGN_RIGHT = 'right'
ALLOWED_ALIGNS = (
    TEXT_ALIGN_LEFT,
    TEXT_ALIGN_RIGHT,
    TEXT_ALIGN_CENTER,
)

TEXT_BASELINE_TOP = 'top'
TEXT_BASELINE_MIDDLE = 'middle'
TEXT_BASELINE_BOTTOM = 'bottom'
ALLOWED_BASELINES = (
    TEXT_BASELINE_TOP,
    TEXT_BASELINE_MIDDLE,
    TEXT_BASELINE_BOTTOM,
)

DEFAULT_LINE_SPACING = 1.2
DEFAULT_STROKE_WIDTH = 1
DEFAULT_BORDER_STYLE = 'S'

LINE_CAP_BUTT = 'butt'
LINE_CAP_ROUND = 'round'
LINE_CAP_SQUARE = 'square'
ALLOWED_LINE_CAPS = (
    LINE_CAP_BUTT,
    LINE_CAP_ROUND,
    LINE_CAP_SQUARE,
)

LINE_JOIN_MITER = 'miter'
LINE_JOIN_ROUND = 'round'
LINE_JOIN_BEVEL = 'bevel'
ALLOWED_LINE_JOINS = (
    LINE_JOIN_MITER,
    LINE_JOIN_ROUND,
    LINE_JOIN_BEVEL,
)

BLACK = (0, 0, 0)
TRANSPARENT = tuple()
